# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Sattar Vakili
description: >- # this means to ignore newlines until "baseurl:"
  This is Sattar"'"s personal website.
baseurl: "/" # the subpath of the site
url: "https://sattar-vakili.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile_pic_sattar.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
    - name: Projects
    - name: Brief Bio

footer:
  show_powered_by: FALSE
  contact:
    - name: Email
      value: sv388[at]cornell.edu
      link: mailto:sv388@cornell.edu
  follow:
    - name: GoogleScholar
      link: https://scholar.google.com/citations?user=N9xs8w0AAAAJ&hl=en

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
