title: Sattar Vakili
description: Principal AI Research Manager at MediaTek Research
url: "https://sattar-vakili.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

header_pages:
  - index.md
  - publications.md
  - cv.md
